package integration

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"media_processing_pipeline/internal/config"
	"media_processing_pipeline/internal/handlers"
	"media_processing_pipeline/internal/job"
	"media_processing_pipeline/internal/queue"

	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	minio "github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	miniodriver "github.com/testcontainers/testcontainers-go/modules/minio"
)

type MockJobStore struct{}

func (mjs *MockJobStore) GetStatus(jobID string) job.JobStatus { return job.JobStatusPending }
func (mjs *MockJobStore) Get(jobID string) (*job.Job, bool)    { return nil, false }

type MockWorkerPool struct {
	Queue    *queue.Queue
	JobStore *MockJobStore
}

func (mwp *MockWorkerPool) Start()                               {}
func (mwp *MockWorkerPool) GetJob(jobID string) (*job.Job, bool) { return mwp.JobStore.Get(jobID) }
func (mwp *MockWorkerPool) Submit(job *job.Job)                  {}
func (mwp *MockWorkerPool) GetQueue() *queue.Queue               { return mwp.Queue }
func (mwp *MockWorkerPool) GetJobStatus(jobID string) job.JobStatus {
	return mwp.JobStore.GetStatus(jobID)
}
func (mwp *MockWorkerPool) GetJobStore() *job.JobStore { return nil }

func TestIngestService(t *testing.T) {
	// create top level background context
	ctx := context.Background()

	// run minio client container
	minioContainer, err := miniodriver.Run(
		ctx,
		"minio/minio:latest", // minio client image name
	)

	if err != nil {
		t.Fatal(err)
	}

	defer minioContainer.Terminate(ctx)

	// get minio client endpoint (random) for generated by container
	endpoint, _ := minioContainer.ConnectionString(ctx)

	t.Logf("endpoint: %s", endpoint)

	// create minio client
	realClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
		Secure: false,
	})

	if err != nil {
		t.Fatalf("failed to create minio realClient: %v", err)
	}

	// create minio client S3 bucket
	realClient.MakeBucket(ctx, "videos", minio.MakeBucketOptions{})

	videoFilePath := filepath.Join("..", "testdata", "test_video.mp4")

	t.Logf("video file path: %s", videoFilePath)

	file, err := os.Open(videoFilePath)
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, _ := writer.CreateFormFile("file", "tiny_test_video.mp4")

	_, err = io.Copy(part, file)
	if err != nil {
		t.Fatal(err)
	}

	writer.Close()

	req := httptest.NewRequest("POST", "/api/upload", body)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	rec := httptest.NewRecorder()

	mockPool := &MockWorkerPool{}

	mockPool.Start()

	handler := handlers.NewHandler(
		mockPool,
		realClient,
		&config.Env{
			MinioBucketName: "videos",
		},
	)

	uploadHandler := handler.UploadHandler
	uploadHandler(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", rec.Code)
	}

	responseBody := rec.Body.Bytes()
	uploadResponse := &handlers.UploadResponse{}

	err = json.Unmarshal(responseBody, uploadResponse)
	if err != nil {
		t.Fatalf("Failed to parse json: %s", err)
	}

	if uploadResponse.Data.VideoID == "" {
		t.Errorf("Expected video ID, got empty string")
	}
}
