package tests

import (
	"context"
	"media_processing_pipeline/internal/config"
	"media_processing_pipeline/internal/jobs"
	"media_processing_pipeline/internal/queue"
	"media_processing_pipeline/internal/worker"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	minio "github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	miniodriver "github.com/testcontainers/testcontainers-go/modules/minio"
)

func TestJobStatusFlow(t *testing.T) {

	// create top level background context
	ctx := context.Background()

	// run minio client container
	minioContainer, err := miniodriver.Run(
		ctx,
		"minio/minio:latest", // minio client image name
	)

	if err != nil {
		t.Fatal(err)
	}

	defer minioContainer.Terminate(ctx)

	// get minio client endpoint (random) for generated by container
	endpoint, _ := minioContainer.ConnectionString(ctx)

	t.Logf("endpoint: %s", endpoint)

	// create minio client
	realClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
		Secure: false,
	})

	if err != nil {
		t.Fatalf("failed to create minio realClient: %v", err)
	}

	// create minio client S3 bucket
	realClient.MakeBucket(ctx, "videos", minio.MakeBucketOptions{})

	// path to real video file for testing
	videoFilePath := filepath.Join("..", "testdata", "tiny_test_video.mp4")

	// open video file
	file, err := os.Open(videoFilePath)
	if err != nil {
		t.Fatalf("Error opening file: %s", err)
	}

	defer file.Close()

	objectName := "test-video.mp4"

	stat, err := file.Stat()
	if err != nil {
		t.Log("stat error: ", err)
	}

	// access the file size
	objectSize := stat.Size()

	putInfo, err := realClient.PutObject(
		ctx,
		"videos",
		objectName,
		file,
		objectSize,
		minio.PutObjectOptions{
			ContentType: "video/mp4",
		},
	)

	if err != nil {
		t.Fatalf("Error in putting object: %d", err)
	}

	t.Logf("size of object put: %d", putInfo.Size)

	// initialize queue
	queue := queue.InitQueue(10)

	// create wait group
	wg := &sync.WaitGroup{}

	// create worker pool
	pool := &worker.WorkerPool{
		Queue:         queue,
		WorkerCount:   3,
		StorageClient: realClient,
		Env: &config.Env{
			MinioBucketName: "videos",
		},
		WaitGroup: wg,
	}

	// create videoID from objectName
	videoID := strings.Split(objectName, ".")[0]
	jobID := videoID

	// create job
	job := jobs.Job{
		VideoID: videoID,
		FileKey: objectName,
	}

	pool.Start()

	jobs.Jobs = make(map[string]jobs.JobStatus)

	pool.Submit(job)

	status := jobs.GetStatus(jobID)

	t.Logf("status instantly after submit: %s", status)

	if status != jobs.JobStatusPending && status != jobs.JobStatusProcessing {
		t.Fatalf(
			"Expected status to be %s or %s, got %s",
			jobs.JobStatusPending,
			jobs.JobStatusProcessing,
			status,
		)
	}

	pool.WaitGroup.Wait()

	status = jobs.GetStatus(jobID)

	t.Logf("status after process completed: %s", status)

	if status != "completed" {
		t.Fatalf("Expected status to be: %s, got %s", "completed", status)
	}

}
