package integration

import (
	"context"
	"media_processing_pipeline/internal/config"
	"media_processing_pipeline/internal/job"
	"media_processing_pipeline/internal/queue"
	"media_processing_pipeline/internal/worker"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	minio "github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	miniodriver "github.com/testcontainers/testcontainers-go/modules/minio"
)

func TestTranscodingJob(t *testing.T) {
	// create top level background context
	ctx := context.Background()

	// run minio client container
	minioContainer, err := miniodriver.Run(
		ctx,
		"minio/minio:latest", // minio client image name
	)

	if err != nil {
		t.Fatal(err)
	}

	defer minioContainer.Terminate(ctx)

	// get minio client endpoint (random) for generated by container
	endpoint, _ := minioContainer.ConnectionString(ctx)

	t.Logf("endpoint: %s", endpoint)

	// create minio client
	realClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
		Secure: false,
	})

	if err != nil {
		t.Fatalf("failed to create minio realClient: %v", err)
	}

	// create minio client S3 bucket
	realClient.MakeBucket(ctx, "videos", minio.MakeBucketOptions{})

	// path to real video file for testing
	videoFilePath := filepath.Join("..", "testdata", "tiny_test_video.mp4")

	// open video file
	file, err := os.Open(videoFilePath)
	if err != nil {
		t.Fatalf("Error opening file: %s", err)
	}

	defer file.Close()

	objectName := "test-video.mp4"

	stat, err := file.Stat()
	if err != nil {
		t.Log("stat error: ", err)
	}

	// access the file size
	objectSize := stat.Size()

	// first put (write) the file in the minio client bucket so that we can get (read) it further
	putInfo, err := realClient.PutObject(
		ctx,
		"videos",
		objectName,
		file,
		objectSize,
		minio.PutObjectOptions{
			ContentType: "video/mp4",
		},
	)

	if err != nil {
		t.Fatalf("Error in putting object: %d", err)
	}

	t.Logf("size of object put: %d", putInfo.Size)

	jobStore := job.NewJobStore()
	// initialize queue
	queue, _ := queue.NewQueue(10)
	// create wait group
	wg := &sync.WaitGroup{}

	// create worker pool
	pool, _ := worker.NewWorkerPool(
		queue,
		3,
		&config.Env{
			MinioBucketName: "videos",
		},
		realClient,
		wg,
		jobStore,
	)

	pool.Start()

	// create videoID from objectName
	videoID := strings.Split(objectName, ".")[0]
	payload := map[string]string{
		"video_id": videoID,
	}
	// create job
	job := job.NewJob(
		job.JobTypeTranscoding,
		payload,
		job.JobStatusPending,
	)

	// pass the job for ffmpeg processing
	pool.TranscodingJob(1, job)

	// wait for job to finish
	pool.WaitGroup.Wait()

	// define output path
	outputPath := filepath.Join("output", videoID, "index.m3u8")

	// use output as assertion
	_, err = os.Stat(outputPath)
	if err != nil {
		t.Fatal("HLS playlist not generated")
	}

}
