package tests

import (
	"bytes"
	"context"
	"io"
	"media_processing_pipeline/internal/config"
	"media_processing_pipeline/internal/handlers"
	"media_processing_pipeline/internal/jobs"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	minio "github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	miniodriver "github.com/testcontainers/testcontainers-go/modules/minio"
)

type MockWorkerPool struct{}

func (mwp *MockWorkerPool) Start()              {}
func (mwp *MockWorkerPool) Submit(job jobs.Job) {}
func (mwp *MockWorkerPool) GetQueue() chan jobs.Job {return nil}

func TestUploadFakeFileToStore(t *testing.T) {

	// create top level background context
	ctx := context.Background()

	// run minio client container
	minioContainer, err := miniodriver.Run(
		ctx,
		"minio/minio:latest", // minio client image name
	)

	if err != nil {
		t.Fatal(err)
	}

	defer minioContainer.Terminate(ctx)

	// get minio client endpoint (random) for generated by container
	endpoint, _ := minioContainer.ConnectionString(ctx)

	t.Logf("endpoint: %s", endpoint)

	// create minio client
	realClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
		Secure: false,
	})

	if err != nil {
		t.Fatalf("failed to create minio realClient: %v", err)
	}

	// create minio client S3 bucket
	realClient.MakeBucket(ctx, "videos", minio.MakeBucketOptions{})

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, _ := writer.CreateFormFile("file", "tiny_test_video.mp4")
	part.Write([]byte("This is fake video data"))

	writer.Close()

	req := httptest.NewRequest("POST", "/api/upload", body)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	rec := httptest.NewRecorder()

	mockPool := &MockWorkerPool{}

	mockPool.Start()

	handler := &handlers.Handler{
		Pool:          mockPool,
		StorageClient: realClient,
		Env: &config.Env{
			MinioBucketName: "videos",
		},
	}

	uploadHandler := handler.UploadHandler()
	uploadHandler.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", rec.Code)
	}

	expectedPrefix := "Uploaded"
	if !bytes.HasPrefix(rec.Body.Bytes(), []byte(expectedPrefix)) {
		t.Errorf("expected response to start with %s, got %s", expectedPrefix, rec.Body.String())
	}

}

func TestUploadRealFileToStore(t *testing.T) {
	// create top level background context
	ctx := context.Background()

	// run minio client container
	minioContainer, err := miniodriver.Run(
		ctx,
		"minio/minio:latest", // minio client image name
	)

	if err != nil {
		t.Fatal(err)
	}

	defer minioContainer.Terminate(ctx)

	// get minio client endpoint (random) for generated by container
	endpoint, _ := minioContainer.ConnectionString(ctx)

	t.Logf("endpoint: %s", endpoint)

	// create minio client
	realClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4("minioadmin", "minioadmin", ""),
		Secure: false,
	})

	if err != nil {
		t.Fatalf("failed to create minio realClient: %v", err)
	}

	// create minio client S3 bucket
	realClient.MakeBucket(ctx, "videos", minio.MakeBucketOptions{})

	videoFilePath := filepath.Join("..", "testdata", "tiny_test_video.mp4")

	t.Logf("video file path: %s", videoFilePath)

	file, err := os.Open(videoFilePath)
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, _ := writer.CreateFormFile("file", "tiny_test_video.mp4")

	_, err = io.Copy(part, file)
	if err != nil {
		t.Fatal(err)
	}

	writer.Close()

	req := httptest.NewRequest("POST", "/api/upload", body)
	req.Header.Set("Content-Type", writer.FormDataContentType())
	rec := httptest.NewRecorder()

	mockPool := &MockWorkerPool{}

	mockPool.Start()

	handler := &handlers.Handler{
		Pool:          mockPool,
		StorageClient: realClient,
		Env: &config.Env{
			MinioBucketName: "videos",
		},
	}

	uploadHandler := handler.UploadHandler()
	uploadHandler.ServeHTTP(rec, req)

	if rec.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", rec.Code)
	}

	expectedPrefix := "Uploaded"
	if !bytes.HasPrefix(rec.Body.Bytes(), []byte(expectedPrefix)) {
		t.Errorf("expected response to start with %s, got %s", expectedPrefix, rec.Body.String())
	}
}
