name: CI Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5 
        with:
          go-version: "1.25.5"
          cache: true
      
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v -race ./...

      - name: Build Binary
        run: go build -o main ./cmd/api
        
